### ISSUE TITLE
Question about stereo calibration (Realsense D435i)

### ISSUE THREAD

**Issue by msadowski** [UZ-SLAMLab/ORB_SLAM3#132]
Hi!

Thanks for a nice package, it looks very promising!

I have a question about stereo calibration. As some advised in some of the issues I've tried using kalibr to perform the calibration of the camera. I have some issues about mapping the output of kalibr to the format specified in the .yaml files in this repository.

Here is an output I've received from kalibr:
```
cam0:
  T_cam_imu:
  - [0.6115078243794958, 0.7841880450352785, -0.1053911322000213, 0.029832061672344146]
  - [-0.7715875066602782, 0.6205080660963369, 0.14008018944575276, -0.0059936755576905235]
  - [0.17524525753477502, -0.004341650968321703, 0.9845152359300685, -0.01565809593685376]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.001578299852444971, 0.0004161890835813036, -3.0486866567158216e-05,
    0.0004105279578233116]
  distortion_model: radtan
  intrinsics: [385.16239130729036, 385.1109410692702, 320.10029939102327, 240.20959343149653]
  resolution: [640, 480]
  rostopic: /rs_d435i/infra1/image_rect_raw
cam1:
  T_cam_imu:
  - [0.6118104191910869, 0.7839881703191637, -0.10512164272326141, -0.013803567601740185]
  - [-0.7713571194974588, 0.6207578549907584, 0.14024221785131613, -0.005996473003320335]
  - [0.17520332522475146, -0.004715322564045513, 0.9845209802555288, -0.015767632493523556]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.9999998979309502, -0.00031975211280364476, 0.00031921258773363404, -0.04363254445825418]
  - [0.0003196886603776441, 0.99999992913703, 0.00019880919541621174, -9.221868736843664e-06]
  - [-0.000319276134773561, -0.00019870712647939776, 0.9999999292891117, -0.00010120398457171706]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.004371210413379108, -0.003213997849267982, -0.0001952677826327911,
    0.0007474849899976242]
  distortion_model: radtan
  intrinsics: [385.0547503305172, 385.0583239097267, 319.79447559991206, 239.98556815146034]
  resolution: [640, 480]
  rostopic: /rs_d435i/infra2/image_rect_raw
```

Looking at [EuroC.yaml](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Examples/Stereo-Inertial/EuRoC.yaml) for Stereo-Inertial:

* There is a set of parameters for Calibration and Distortion (Camera.fx...Camera.p2) - does this means that both of the cameras in the stereo setup should ideally have the same values for these parameters? Can I somehow split them by camera?
* Are IMU.* LEFT.* RIGHT.* parameter suffixes fixed? I assume I never have to change them with any topic changes etc?
* Any tips on mapping kalibr output to LEFT.D, LEFT.K, LEFT.R, LEFT.Rf, LEFT.P ?
