### ISSUE TITLE
Not stable RGB-D Inertial tracking (real time test on car)

### ISSUE THREAD

**Issue by Userpc1010** [UZ-SLAMLab/ORB_SLAM3#722]
When running the RGB-D Inertial example on an Intel D455 camera, it takes a lot of movement to initialize and intermittently loses indoor tracking, calibrating the camera and imu sensors in kalibr did not significantly improve tracking. Is this the correct operation of ORB SLAM3 why does it take a lot of movement to initialize RGB-D like in the Monocular example?

https://www.youtube.com/watch?v=uDNA8HNGIoI&t=345s

My .yaml file:
```
%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 640.338
Camera1.fy: 638.673
Camera1.cx: 639.555
Camera1.cy: 362.661

Camera1.p1: 636.7834799899963
Camera1.p2: 364.1529749187936

# distortion parameters
Camera1.k1: -0.046595600657165025
Camera1.k2: 0.026160859189839854
Camera1.k3: -0.0003504572160801618
Camera1.k4: -0.0011346820837702665

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 60.0
Stereo.b: 0.094978

# Depth map values factor
RGBD.DepthMapFactor: 580.0  #1000 #current value tracking is more stable

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.9999410690311243, -0.0010983044171098205, 0.010800564443530714, -0.03416629640347083,
          0.0010513719550017482, 0.9999899856191709, 0.004350089468284401, -0.007858402423165139,
          -0.01080523400504305, -0.004338477702743224, 0.9999322099669149, -0.029943907325837224,
          0.0,                    0.0,                    0.0,                 1.0                 ]
          

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 1 #test for configure imu

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.015545769517023996 # rad/s^0.5 #test for configure imu
IMU.NoiseAcc: 0.15368276926571492  # m/s^1.5 #test for configure imu
IMU.GyroWalk: 2.37929770927606e-06 # rad/s^1.5
IMU.AccWalk:  4.116687773725591e-05 # m/s^2.5
IMU.Frequency: 400.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.5

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0`

```
RGB Camera calib:

```
  cam0:
  T_cam_imu:
  - [0.9999410690311243, -0.0010983044171098205, 0.010800564443530714, -0.03416629640347083]
  - [0.0010513719550017482, 0.9999899856191709, 0.004350089468284401, -0.007858402423165139]
  - [-0.01080523400504305, -0.004338477702743224, 0.9999322099669149, -0.029943907325837224]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.046595600657165025, 0.026160859189839854, -0.0003504572160801618, -0.0011346820837702665]
  distortion_model: radtan
  intrinsics: [619.8078677901826, 619.6476531771294, 636.7834799899963, 364.1529749187936]
  resolution: [1280, 720]
  rostopic: /camera/color/image_raw
  timeshift_cam_imu: -0.00811566158846955
```
IMU Calib:
```
  imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.0015368276926571492
  accelerometer_random_walk: 4.116687773725591e-05
  gyroscope_noise_density: 0.00015545769517023996
  gyroscope_random_walk: 2.037929770927606e-06
  model: calibrated
  rostopic: /camera/imu
  time_offset: 0.0
  update_rate: 400.0

```
